package dam.gestionhotelera.modelo.Pojos;
// Generated 03-dic-2017 19:50:02 by Hibernate Tools 4.3.1



/**
 * EmpleadoHasParteId generated by hbm2java
 */
public class EmpleadoHasParteId  implements java.io.Serializable {


     private int empleadoIdEmpleado;
     private int parteIdparte;

    public EmpleadoHasParteId() {
    }

    public EmpleadoHasParteId(int empleadoIdEmpleado, int parteIdparte) {
       this.empleadoIdEmpleado = empleadoIdEmpleado;
       this.parteIdparte = parteIdparte;
    }
   
    public int getEmpleadoIdEmpleado() {
        return this.empleadoIdEmpleado;
    }
    
    public void setEmpleadoIdEmpleado(int empleadoIdEmpleado) {
        this.empleadoIdEmpleado = empleadoIdEmpleado;
    }
    public int getParteIdparte() {
        return this.parteIdparte;
    }
    
    public void setParteIdparte(int parteIdparte) {
        this.parteIdparte = parteIdparte;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoHasParteId) ) return false;
		 EmpleadoHasParteId castOther = ( EmpleadoHasParteId ) other; 
         
		 return (this.getEmpleadoIdEmpleado()==castOther.getEmpleadoIdEmpleado())
 && (this.getParteIdparte()==castOther.getParteIdparte());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpleadoIdEmpleado();
         result = 37 * result + this.getParteIdparte();
         return result;
   }   


}


